import type { ExpenseCategory, ExpenseSubCategory, SelectOption } from "@/types/finance";

export const expenseSubCategories: Record<ExpenseCategory, SelectOption<ExpenseSubCategory>[]> = {
  food: [
    { value: "homeCooking", label: "自炊" },
    { value: "eatingOut", label: "外食" },
    { value: "cafe", label: "カフェ" },
    { value: "groceries", label: "食材" },
    { value: "convenienceStore", label: "コンビニ" },
    { value: "snacks", label: "おやつ" },
    { value: "drinks", label: "飲み物" },
    { value: "delivery", label: "デリバリー" },
    { value: "other", label: "その他" },
  ],
  daily: [
    { value: "consumables", label: "消耗品" },
    { value: "materials", label: "材料費" },
    { value: "detergent", label: "洗剤" },
    { value: "paperGoods", label: "紙類" },
    { value: "kitchenGoods", label: "キッチン用品" },
    { value: "bathToiletGoods", label: "バス・トイレ用品" },
    { value: "babyGoods", label: "ベビー用品" },
    { value: "petGoods", label: "ペット用品" },
    { value: "other", label: "その他" },
  ],
  housing: [
    { value: "rent", label: "家賃" },
    { value: "mortgage", label: "住宅ローン" },
    { value: "managementFee", label: "管理費" },
    { value: "repairReserve", label: "修繕積立金" },
    { value: "parking", label: "駐車場" },
    { value: "furniture", label: "家具" },
    { value: "appliances", label: "家電" },
    { value: "moving", label: "引っ越し" },
    { value: "other", label: "その他" },
  ],
  utility: [
    { value: "electricity", label: "電気" },
    { value: "gas", label: "ガス" },
    { value: "water", label: "水道" },
    { value: "other", label: "その他" },
  ],
  communication: [
    { value: "mobile", label: "携帯" },
    { value: "internet", label: "インターネット" },
    { value: "landline", label: "固定電話" },
    { value: "device", label: "通信機器" },
    { value: "other", label: "その他" },
  ],
  transport: [
    { value: "train", label: "電車" },
    { value: "bus", label: "バス" },
    { value: "parking", label: "駐車場" },
    { value: "inspection", label: "点検・整備" },
    { value: "other", label: "その他" },
  ],
  entertainment: [
    { value: "movie", label: "映画" },
    { value: "music", label: "音楽" },
    { value: "game", label: "ゲーム" },
    { value: "travel", label: "旅行" },
    { value: "event", label: "イベント" },
    { value: "hobby", label: "趣味" },
    { value: "oshiKatsu", label: "推し活" },
    { value: "other", label: "その他" },
  ],
  beautyClothing: [
    { value: "clothing", label: "服" },
    { value: "shoes", label: "靴" },
    { value: "bag", label: "バッグ" },
    { value: "cosmetics", label: "コスメ" },
    { value: "hairSalon", label: "美容院" },
    { value: "nail", label: "ネイル" },
    { value: "skinCare", label: "スキンケア" },
    { value: "bodyCare", label: "ボディケア" },
    { value: "tops", label: "トップス" },
    { value: "other", label: "その他" },
  ],
  insurance: [
    { value: "lifeInsurance", label: "生命保険" },
    { value: "medicalInsurance", label: "医療保険" },
    { value: "cancerInsurance", label: "がん保険" },
    { value: "carInsurance", label: "自動車保険" },
    { value: "fireInsurance", label: "火災保険" },
    { value: "personalPension", label: "個人年金" },
    { value: "nationalPension", label: "国民年金" },
    { value: "nationalHealthInsurance", label: "国民健康保険" },
    { value: "other", label: "その他" },
  ],
  tax: [
    { value: "residentTax", label: "住民税" },
    { value: "incomeTax", label: "所得税" },
    { value: "other", label: "その他" },
  ],
  medical: [
    { value: "hospital", label: "病院" },
    { value: "dental", label: "歯科" },
    { value: "medicine", label: "薬" },
    { value: "contactsGlasses", label: "コンタクト・眼鏡" },
    { value: "inspection", label: "検査" },
    { value: "other", label: "その他" },
  ],
  education: [
    { value: "tuition", label: "学費" },
    { value: "materials", label: "教材" },
    { value: "cramSchool", label: "塾" },
    { value: "qualification", label: "資格" },
    { value: "books", label: "書籍" },
    { value: "seminar", label: "セミナー" },
    { value: "other", label: "その他" },
  ],
  other: [{ value: "other", label: "その他" }],
}